name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  perform-checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP with JIT in tracing mode
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.2'
          coverage: pcov

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: ./vendor
        key: ${{ runner.os }}-composer-vendor-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
            ${{ runner.os }}-composer-vendor-

    - name: Install dependencies
      run: composer install --no-progress

    - name: Check style
      run: composer run-script cs

    - name: Run tests
      run: php ./vendor/bin/phpunit --coverage-clover coverage.xml

    - name: Static analysis
      run: composer run-script stan

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: JanisVepris/gs1-decoder
